
--Q1
CREATE TABLE CUSTOMER(CUSTNO NUMBER(3) PRIMARY KEY, CNAME VARCHAR2(25) UNIQUE, CITY VARCHAR2(12), GENDER CHAR(1) 
CHECK (GENDER='M' OR GENDER='F'), PHONE VARCHAR2(6));
CREATE TABLE ITEM(ITEMNO NUMBER(3) PRIMARY KEY, UNITPRICE NUMBER(6,2));
CREATE TABLE ORDERS(ORDERNO NUMBER(3) PRIMARY KEY, ODATE DATE NOT NULL, CUSTNO NUMBER(3), ORD_AMT NUMBER(5), FOREIGN KEY
(CUSTNO) REFERENCES CUSTOMER(CUSTNO));
CREATE TABLE ORDER_ITEM(ORDERNO NUMBER(3) PRIMARY KEY, ITEMNO NUMBER(3), QTY NUMBER(5), FOREIGN KEY (ITEMNO) REFERENCES
ITEM (ITEMNO));
CREATE TABLE WAREHOUSE(WAREHOUSENO VARCHAR2(3) PRIMARY KEY, CITY VARCHAR2(12));
CREATE TABLE SHIPMENT(ORDERNO NUMBER(3) PRIMARY KEY, WAREHOUSENO VARCHAR2(3), SHIP_DATE DATE, FOREIGN KEY (WAREHOUSENO) 
REFERENCES WAREHOUSE(WAREHOUSENO));

--Q2
CREATE SEQUENCE SEQUENCE1
MINVALUE 11
MAXVALUE 999
INCREMENT BY 11;

--Q3
CREATE SEQUENCE SEQUENCE2
MINVALUE 21
MAXVALUE 99
INCREMENT BY 1;

--Q4
CREATE SEQUENCE SEQUENCE3
MINVALUE 1
MAXVALUE 999
INCREMENT BY 1;

--Q5
INSERT INTO CUSTOMER VALUES(SEQUENCE1.NEXTVAL,'SARA','DOHA','F',111111);
INSERT INTO CUSTOMER VALUES(SEQUENCE1.NEXTVAL,'FATMA','DOHA','F',222222);
INSERT INTO CUSTOMER VALUES(SEQUENCE1.NEXTVAL,'OMAR','KHOR','M',333333);
INSERT INTO CUSTOMER VALUES(SEQUENCE1.NEXTVAL,'ALI','SHIMAL','M',444444);
INSERT INTO CUSTOMER VALUES(SEQUENCE1.NEXTVAL,'HASSAN','KHOR','M',555555);
SELECT * FROM CUSTOMER;
INSERT INTO ORDERS VALUES(SEQUENCE2.NEXTVAL,'03-04-2002',11,100);
INSERT INTO ORDERS VALUES(SEQUENCE2.NEXTVAL,'09-03-2004',22,110);
INSERT INTO ORDERS VALUES(SEQUENCE2.NEXTVAL,'23-01-2001',33,140);
INSERT INTO ORDERS VALUES(SEQUENCE2.NEXTVAL,'11-08-2008',44,160);
INSERT INTO ORDERS VALUES(SEQUENCE2.NEXTVAL,'06-10-2010',55,200);
SELECT * FROM ORDERS;
INSERT INTO ITEM VALUES(SEQUENCE3.NEXTVAL,1100);
INSERT INTO ITEM VALUES(SEQUENCE3.NEXTVAL,1200);
INSERT INTO ITEM VALUES(SEQUENCE3.NEXTVAL,1300);
INSERT INTO ITEM VALUES(SEQUENCE3.NEXTVAL,1400);
INSERT INTO ITEM VALUES(SEQUENCE3.NEXTVAL,1500);
SELECT * FROM ITEM;
INSERT INTO ORDER_ITEM VALUES(21,1,200);
INSERT INTO ORDER_ITEM VALUES(25,5,200);
INSERT INTO ORDER_ITEM VALUES(22,2,250);
INSERT INTO ORDER_ITEM VALUES(24,4,300);
INSERT INTO ORDER_ITEM VALUES(23,3,600);
SELECT * FROM ORDER_ITEM;
INSERT INTO WAREHOUSE VALUES('W1','NAJMA');
INSERT INTO WAREHOUSE VALUES('W2','KHOR');
INSERT INTO WAREHOUSE VALUES('W3','DOHA');
INSERT INTO WAREHOUSE VALUES('W4','MUNTZA');
INSERT INTO WAREHOUSE VALUES('W5','RAYAAN');
SELECT * FROM WAREHOUSE;
INSERT INTO SHIPMENT VALUES(21,'W1','01-11-2002');
INSERT INTO SHIPMENT VALUES(25,'W2','24-12-2010');
INSERT INTO SHIPMENT VALUES(22,'W3','13-05-2005');
INSERT INTO SHIPMENT VALUES(24,'W4','16-09-2008');
INSERT INTO SHIPMENT VALUES(23,'W5','28-04-2001');
SELECT * FROM SHIPMENT;

--Q6
CREATE VIEW CUSTOMERS_VW
AS SELECT C.*,D.ORDERNO, D.ODATE, D.ORD_AMT
FROM CUSTOMER C, ORDERS D
WHERE C.CUSTNO=D.CUSTNO;
SELECT * FROM CUSTOMERS_VW;

--Q7
CREATE VIEW WAREHOUSE_VW
AS SELECT C.CNAME,D.ORDERNO, E.WAREHOUSENO
FROM CUSTOMER C, ORDERS D, SHIPMENT E
WHERE C.CUSTNO=D.CUSTNO
AND D.ORDERNO=E.ORDERNO
AND C.CNAME='FATMA';
SELECT * FROM WAREHOUSE_VW;

--Q8
CREATE VIEW SUMMARY_VW
AS SELECT CNAME, COUNT(ORDERNO) AS NO_OF_ORDERS, AVG(ORD_AMT) AS AVG_ORDER_AMT
FROM CUSTOMER, ORDERS
WHERE CUSTOMER.CUSTNO=ORDERS.CUSTNO
GROUP BY CNAME;
SELECT * FROM SUMMARY_VW;

--Q9
SELECT O.ORDERNO, S.SHIP_DATE
FROM SHIPMENT S, ORDERS O
WHERE O.ORDERNO=S.ORDERNO 
AND S.WAREHOUSENO='W2';

--Q10
SELECT O.*
FROM ORDERS O
INNER JOIN SHIPMENT S ON O.ORDERNO=S.ORDERNO
WHERE MONTHS_BETWEEN(S.SHIP_DATE,O.ODATE)>12;

--Q11
SELECT O.*
FROM ORDERS O
INNER JOIN SHIPMENT S ON O.ORDERNO=S.ORDERNO
INNER JOIN WAREHOUSE W ON W.WAREHOUSENO=W.WAREHOUSENO
WHERE W.CITY='RAYAAN';

--Q12
SELECT ITEMNO, MAX(UNITPRICE) AS PRICE
FROM ITEM 
GROUP BY ITEMNO;

--Q13
SELECT C.* 
FROM CUSTOMER C 
INNER JOIN ORDERS O ON C.CUSTNO=O.CUSTNO
INNER JOIN SHIPMENT S ON O.ORDERNO=S.ORDERNO
INNER JOIN WAREHOUSE W ON S.WAREHOUSENO=W.WAREHOUSENO
WHERE C.CITY=W.CITY;

--Q14
DELETE FROM ORDERS 
WHERE CUSTNO IN (SELECT CUSTNO FROM CUSTOMER 
WHERE CNAME LIKE 'SARA');

--Q15
DELETE FROM ORDER_ITEM
WHERE ITEMNO IN (SELECT ITEMNO FROM ITEM
WHERE UNITPRICE>(SELECT AVG(UNITPRICE) FROM ITEM));

--Q16
UPDATE CUSTOMER
SET CITY='MAUITHER'
WHERE CITY='DOHA';
SELECT * FROM CUSTOMER;

--Q17
UPDATE ITEM
SET UNITPRICE=UNITPRICE+(UNITPRICE*0.25);
SELECT * FROM ITEM;