--Talha Abdullah --201903446

-- Q1
SELECT * FROM EMP
WHERE COMM>SAL;

-- Q2
SELECT *
FROM EMP
WHERE (SAL+SAL*0.25)>3000;

--Q3
SELECT MANAGER.ENAME || ' MANAGER OF ' || WORKER.ENAME
FROM EMP WORKER, EMP MANAGER
WHERE WORKER.MGR=MANAGER.EMPNO;

--Q4
SELECT EMPNO, ENAME, HIREDATE, SAL
FROM EMP
WHERE HIREDATE<'01-APR-1981';

--Q5
SELECT E.EMPNO, E.ENAME,E.SAL
FROM EMP E, EMP D
WHERE E.MGR=D.EMPNO
AND D.ENAME LIKE 'KING';

--Q6
SELECT * 
FROM EMP
WHERE mod(sal,2)=0;

--Q7
SELECT * 
FROM EMP
WHERE LENGTH(SAL)=3;

--Q8
SELECT * 
FROM EMP 
WHERE TO_CHAR(HIREDATE,'MON') NOT IN ('DEC'); 

--Q9
SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE,'DD-MON-YY') IN ('01-MAY-81','20-FEB-81','03-DEC-81');

--Q10
SELECT * 
FROM EMP
WHERE MGR IN (7902,7698,7788,7782);

--Q11
SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE,'YY') ='80';

--Q12
SELECT E.ENAME, E.JOB, 12*E.SAL AS "ANNUAL SALARY", E.DEPTNO, S.GRADE
FROM EMP E,DEPT D,SALGRADE S
WHERE  E.DEPTNO=D.DEPTNO 
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND ((12*E.SAL)=60000 OR E.JOB != 'ANALYST') ;

--Q13
SELECT E.ENAME, S.HISAL 
FROM EMP E, SALGRADE S
WHERE E.ENAME='SCOTT'
AND E.SAL IN (SELECT S.HISAL FROM SALGRADE); 

--Q14
SELECT * 
FROM EMP
WHERE JOB='ANALYST' OR JOB='MANAGER'
AND SAL>=2000 AND SAL<=5000
AND (COMM=0 OR COMM IS NULL);

--Q15
SELECT D.DEPTNO, E.EMPNO, E.ENAME,E.SAL, D.DNAME,D.LOC, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE D.DEPTNO=E.DEPTNO
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND D.DNAME='SALES'
AND D.LOC IN ('CHICAGO','DALLAS')
AND S.GRADE IN (3,4,5)
AND (MONTHS_BETWEEN(SYSDATE,HIREDATE)>(40*12));

--Q16
SELECT * 
FROM EMP 
ORDER BY EMPNO ASC, JOB DESC;

--Q17
SELECT EMPNO, ENAME, SAL, SAL/30 AS "DAILY_SALARY", (12*SAL+SAL) AS "ANNUAL_SALARY"
FROM EMP
ORDER BY ANNUAL_SALARY ASC;

--Q18
SELECT *
FROM EMP
ORDER BY JOB ASC,EMPNO DESC;

--Q19
SELECT DISTINCT JOB
FROM EMP
WHERE DEPTNO IN (20,30)
ORDER BY JOB DESC;

--Q20
SELECT E.ENAME, E.JOB, E.SAL, S.GRADE, D.DNAME
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO=D.DEPTNO
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND E.JOB!='CLERK'
ORDER BY E.SAL DESC;

--Q21
SELECT JOB, AVG(SAL), AVG(SAL+NVL(COMM,0)) 
FROM EMP
GROUP BY JOB
ORDER BY AVG(SAL) ASC;

--Q22
SELECT COUNT(*)
FROM EMP
WHERE LENGTH(ENAME)=6
AND ENAME LIKE '%N';

--Q23
SELECT * 
FROM EMP
WHERE TO_CHAR(HIREDATE,'MON') LIKE '_A%';

--Q24
SELECT *
FROM EMP
WHERE ENAME LIKE '%AR%';

--Q25
SELECT * 
FROM EMP
WHERE TO_CHAR(HIREDATE,'MONTH') NOT LIKE '%A%';







