CREATE VIEW BEST_RATED_DOCTOR AS
SELECT D.DOC_ID AS "DOCTOR ID", (U.FNAME||' '||U.LNAME) AS "DOCTOR NAME", COUNT(R.RAT_ID) AS "NUMBER OF RATINGS', ROUND(AVG(R.RAT_RATING),2) AS "AVERAGE RATING"
FROM DOCTORS D, RATING R, USERS U
WHERE D.DOCID=R.DOCID
AND U.USERNAME=D.USERNAME
AND R.RAT_DATE>= TO_DATE('2020/01/01','yyyy/mm/dd')
GROUP BY D.DOCID,U.FNAME ||' '|| U.LNAME
ORDER BY AVG(R.RAT_RATING) DESC;

