-- Talha Abdullah Punjabi   201903446

--Q1
SELECT EMPNO,ENAME,SAL 
FROM EMP
WHERE SAL>(
SELECT AVG(SAL) 
FROM EMP 
);

--Q2
SELECT ENAME,SAL 
FROM EMP
WHERE (SAL<=800 OR SAL>=2000);

--Q3
SELECT E.ENAME, E.JOB, E.SAL, D.DNAME, S.GRADE 
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO=D.DEPTNO
AND (E.SAL BETWEEN S.LOSAL AND S.HISAL)
ORDER BY E.ENAME;

--Q4
SELECT EMPNO AS "ID", ENAME AS "NAME", SAL AS "SALARY", ROUND(MONTHS_BETWEEN(SYSDATE,HIREDATE)) AS "MONTHS WORKED"
FROM EMP 
WHERE (COMM IS NOT NULL AND COMM>0);

--Q5
SELECT ROUND((SELECT AVG(SAL) FROM EMP)-S.LOSAL) "DIFFERENCE"
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO=D.DEPTNO
AND (E.SAL BETWEEN S.LOSAL AND S.HISAL)
GROUP BY E.DEPTNO;


