
DROP TABLE REPLY;
DROP TABLE TOPIC;
DROP TABLE TOPIC_TYPE;
DROP TABLE RATING;
DROP TABLE DOCTORS;
DROP TABLE POSITION;
DROP TABLE PATIENT_MEDICINE;
DROP TABLE PATIENT;
DROP TABLE MEDICINE;
DROP TABLE USERS;
DROP TABLE USER_TYPE;
DROP TABLE SPECIALITY;

CREATE TABLE POSITION
(
POSID NUMBER(3) PRIMARY KEY,
POS_NAME VARCHAR(100) NOT NULL,
POS_DESCRPTION VARCHAR(150) NOT NULL
);

CREATE TABLE SPECIALITY
(
SPEC_ID NUMBER(3) PRIMARY KEY,
SPEC_NAME VARCHAR(100) NOT NULL,
SPEC_DESC VARCHAR(150) NOT NULL,
CONSTRAINT CHK_SPECIALITY CHECK(SPEC_NAME='ENT' OR SPEC_NAME='NEUROLOGY' OR SPEC_NAME='CARDIOLOGY' OR SPEC_NAME='DERMATOLOGY' OR SPEC_NAME='IMMUNOLOGY' OR SPEC_NAME='CARDIOLOGY')
);

CREATE TABLE USER_TYPE
(
USERTYPE_ID NUMBER(1) PRIMARY KEY,
USERTYPE_NAME VARCHAR(100) NOT NULL,
USERTYPE_DESC VARCHAR(150) NOT NULL
);

CREATE TABLE USERS
(
USERNAME VARCHAR2(100) PRIMARY KEY,
PASSWORD VARCHAR2(100) NOT NULL,
DATE_CREATED DATE NOT NULL,
FNAME VARCHAR2(75) NOT NULL,
LNAME VARCHAR2(75) NOT NULL,
USERTYPE_ID NUMBER(1) NOT NULL,
FOREIGN KEY(USERTYPE_ID) REFERENCES USER_TYPE(USERTYPE_ID) ON DELETE CASCADE
);

CREATE TABLE DOCTORS
(
DOC_ID NUMBER(2) PRIMARY KEY,
DOC_BIODATA VARCHAR2(150) NOT NULL,
POSID NUMBER(3) NOT NULL,
SPEC_ID NUMBER(3) NOT NULL,
USERNAME VARCHAR2(100) NOT NULL,
FOREIGN KEY (POSID) REFERENCES POSITION(POSID) ON DELETE CASCADE,
FOREIGN KEY (SPEC_ID) REFERENCES SPECIALITY(SPEC_ID) ON DELETE CASCADE,
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE MEDICINE
(
MED_ID NUMBER(4) PRIMARY KEY,
MED_NAME VARCHAR2(100) NOT NULL,
MED_DESCRIPTION VARCHAR2(100) NOT NULL,
MED_PRICE DECIMAL(10,2) NOT NULL
);

CREATE TABLE PATIENT
(
PAT_ID NUMBER(3) PRIMARY KEY,
PAT_CONDITION VARCHAR2(150) NOT NULL,
USERNAME VARCHAR2(100) NOT NULL,
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE PATIENT_MEDICINE
(
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
PAT_ID NUMBER(3) NOT NULL,
MED_ID NUMBER(4) NOT NULL,
FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID) ON DELETE CASCADE,
FOREIGN KEY (MED_ID) REFERENCES MEDICINE(MED_ID) ON DELETE CASCADE
);

CREATE TABLE RATING
(
RAT_ID NUMBER(4) PRIMARY KEY,
RAT_DATE DATE NOT NULL,
RAT_RATING NUMBER(1) NOT NULL,
RAT_COMMENT VARCHAR(50) NOT NULL,
PAT_ID NUMBER(3) NOT NULL,
DOC_ID NUMBER(2)NOT NULL,
FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID) ON DELETE CASCADE,
FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID) ON DELETE CASCADE,
CONSTRAINT CHECK_RATING CHECK (RAT_RATING>0 AND RAT_RATING<6)
);

CREATE TABLE TOPIC_TYPE
(
TTYPE_ID NUMBER(1) PRIMARY KEY,
T_NAME VARCHAR2(100) NOT NULL,
T_DESCRIPTION VARCHAR2(100) NOT NULL
);

CREATE TABLE TOPIC
(
T_ID NUMBER(3) PRIMARY KEY,
DATE_CREATED DATE NOT NULL,
APPROVED NUMBER(1) NOT NULL,
TITLE VARCHAR2(100) NOT NULL,
SPEC_ID NUMBER(3), 
TTYPE_ID NUMBER(1) NOT NULL,
USERNAME VARCHAR2(100) NOT NULL,
FOREIGN KEY (SPEC_ID) REFERENCES SPECIALITY (SPEC_ID) ON DELETE CASCADE,
FOREIGN KEY (TTYPE_ID) REFERENCES TOPIC_TYPE (TTYPE_ID) ON DELETE CASCADE,
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE,
CONSTRAINT APPROVE_CHCK CHECK (APPROVED=1 OR APPROVED=0)
);

CREATE TABLE REPLY
(
REP_ID NUMBER(3) NOT NULL,
REPLY VARCHAR2(100) NOT NULL,
REPLY_DATE DATE NOT NULL,
T_ID NUMBER(3) NOT NULL,
USERNAME VARCHAR2(100) NOT NULL,
FOREIGN KEY (T_ID) REFERENCES TOPIC (T_ID) ON DELETE CASCADE,
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);